name: Windows
on: 
  push:
permissions:
  contents: write

jobs:
  qmake_build:
    runs-on: [windows-2019]
    strategy:
      matrix:
        include:
          - qt_ver: 6.0.0
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            version: 2019
            qt_arch_install: msvc2019_64
          # 6.2.2
          - qt_ver: 6.2.2
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            version: 2019
            qt_arch_install: msvc2019_64
    env:
      executable: pomodoro
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
      - uses: actions/checkout@v2
      - name: msvc-build
        id: build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.version }}\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          dir
          qmake
          nmake
          dir
          dir .\release
          dir .\debug
          windeployqt release\${{ env.executable }}.exe --release --no-translations --no-opengl-sw --no-system-d3d-compiler --no-compiler-runtime --dir packet
          dir .\packet
      - name: packet
        id: packet
        shell: pwsh
        run: |
          dir
          dir .\packet
          Copy-Item .\release\${{ env.executable }}.exe .\packet
          dir .\packet
          Compress-Archive -Path .\packet\*   ${{ env.executable }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}'.zip'
          dir

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.executable }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}.zip
          path: ${{ env.executable }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.executable }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
  build_cmake:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.1
          arch: win64_msvc2022_64
      - uses: actions/checkout@v2

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
      - name: Setup MSVC Development Environment
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - name: Configure with CMake
        run: |
          mkdir build
          cd build
          cmake ../ -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -DPRODUCTION_OPTIMIZATION=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build application
        run: |
          cd build
          cmake --build . --config Release -j 16
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Deploy
        shell: pwsh
        run: |
          dir
          where.exe windeployqt
          where.exe nmake
          dir .\build
